name: CI
on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - synchronize
jobs:
  ubuntu:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        cabal: ["3.10"]
        ghc:
          - "9.6.6"
          - "9.8.2"
          - "9.10.1"
    steps:
      - uses: actions/checkout@v4
      - uses: haskell-actions/setup@v2
        id: setup-haskell-cabal
        with:
          ghc-version: ${{ matrix.ghc }}
          cabal-version: ${{ matrix.cabal }}
      - run: cabal v2-update
      - run: cabal v2-freeze --allow-newer=servant-jsonrpc:aeson --allow-newer=servant-jsonrpc:servant --allow-newer=servant-jsonrpc-client:aeson --allow-newer=servant-jsonrpc-client:servant --allow-newer=servant-jsonrpc-client:servant-client-core
      - uses: actions/cache@v4
        with:
          path: |
            ${{ steps.setup-haskell-cabal.outputs.cabal-store }}
            dist-newstyle
          key: ${{ runner.os }}-${{ matrix.ghc }}-${{ hashFiles('cabal.project.freeze') }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.ghc }}-
      - run: cabal v2-build  --allow-newer=servant-jsonrpc:aeson --allow-newer=servant-jsonrpc:servant --allow-newer=servant-jsonrpc-client:aeson --allow-newer=servant-jsonrpc-client:servant --allow-newer=servant-jsonrpc-client:servant-client-core
  windows:
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        cabal: ["3.10"]
        ghc:
          - "9.6.6"
          - "9.8.2"
          - "9.10.1"
        winio: [true]
    steps:
      - uses: actions/checkout@v4
      - uses: haskell-actions/setup@v2
        id: setup-haskell-cabal
        with:
          ghc-version: ${{ matrix.ghc }}
          cabal-version: ${{ matrix.cabal }}
      - run: cabal v2-update
      - run: cabal v2-freeze --allow-newer=servant-jsonrpc:aeson --allow-newer=servant-jsonrpc:servant --allow-newer=servant-jsonrpc-client:aeson --allow-newer=servant-jsonrpc-client:servant --allow-newer=servant-jsonrpc-client:servant-client-core
      - uses: actions/cache@v4
        with:
          path: |
            ${{ steps.setup-haskell-cabal.outputs.cabal-store }}
            dist-newstyle
          key: ${{ runner.os }}-${{ matrix.ghc }}-${{ hashFiles('cabal.project.freeze') }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.ghc }}-
      - run: cabal v2-build  --allow-newer=servant-jsonrpc:aeson --allow-newer=servant-jsonrpc:servant --allow-newer=servant-jsonrpc-client:aeson --allow-newer=servant-jsonrpc-client:servant --allow-newer=servant-jsonrpc-client:servant-client-core
      - if: matrix.winio
        run: cabal v2-build --ghc-option=-with-rtsopts=--io-manager=native  --allow-newer=servant-jsonrpc:aeson --allow-newer=servant-jsonrpc:servant --allow-newer=servant-jsonrpc-client:aeson --allow-newer=servant-jsonrpc-client:servant --allow-newer=servant-jsonrpc-client:servant-client-core
